
services:
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
       - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  saga-orchestrator:
    build: saga-orchestrator
    container_name: saga-orchestrator
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3002:3002"
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq

  warehouse-service:
    build: ./warehouse-service
    container_name: warehouse-service
    ports:
      - "3003:3003"
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge
